### ISSUE TITLE
Open source this textbook

### ISSUE THREAD

**Issue by siddharthist** [OpenIntroOrg/randomization-and-simulation#1]
I'm using this in my class and I would like to point out specific issues with this textbook. It's much easier to do so with Github's links to specific lines of code :smile: 

Is there anything in particular holding up the release of the source?

**Comment by mine-cetinkaya-rundel** [comment]
Hi - The book files for 1st edition are now in the master branch of this repo. We happen to be working on a 2nd edition currently, so any feedback is much appreciated. 2nd edition files will be on the edition2 branch, and will be updated over the next few months. Comments on 1st edition (which is what you're using) should go on the master branch. Thanks for the feedback!

**Comment by siddharthist** [comment]
Thank you so much!
