### ISSUE TITLE
\oiRedirect{}?

### ISSUE THREAD

**Issue by beanumber** [OpenIntroOrg/randomization-and-simulation#4]
I had to add:
```
\newcommand{\oiRedirect}[1]{\url{#1}}
```
to `main.tex` in order to get this to compile. Am I missing something? Where is `\oiRedirect{}` defined?

**Comment by mine-cetinkaya-rundel** [comment]
\oiRedirect{} is used for dead URLs, i.e. in case URL dies after publication.

Closing this issue since the same conversation is in the PR as well.
